version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - 'typescript-eslint'
          - '@eslint/*'
      test:
        patterns:
          - 'jest'
          - 'ts-jest'
          - '@types/jest'
          - 'supertest'
          - '@types/supertest'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
