import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import {
  TAdmin,
  TProductCategory,
  TProductAttributeCategory,
  TProductAttribute,
  TProductCategoryAttributeRelation,
  TProductSpu,
  TProductSku,
  TProductBrand,
  TProductGroup,
  TProductGroupRelation,
  TSwiper,
  TCustomer,
  TCustomerAddress,
  TOrder,
  TOrderItem,
  TCustomerLevel,
  TOrderOperateHistory,
  TOrderPayLog,
  TOrderReturnApply,
  TOrderReturnReason,
  TCustomerRelation,
  TAccount,
  TCustomerWallet,
  TCustomerWalletLog,
  TCustomerProfit,
  TOrderDelivery,
  TOrderDeliveryItem,
  TDeliveryCompany,
  TArea,
  TAccountLoginLog,
  TAccountPlatform,
  TCartItem,
  TThirdPlatformConfig,
} from '@models/index';

@Module({
  imports: [
    SequelizeModule.forFeature([
      TAdmin,
      TProductCategory,
      TProductAttributeCategory,
      TProductAttribute,
      TProductCategoryAttributeRelation,
      TProductSpu,
      TProductSku,
      TProductBrand,
      TProductGroup,
      TProductGroupRelation,
      TSwiper,
      TCustomer,
      TCustomerAddress,
      TOrder,
      TOrderItem,
      TCustomerLevel,
      TOrderOperateHistory,
      TOrderPayLog,
      TOrderReturnApply,
      TOrderReturnReason,
      TCustomerRelation,
      TAccount,
      TCustomerWallet,
      TCustomerWalletLog,
      TCustomerProfit,
      TOrderDelivery,
      TOrderDeliveryItem,
      TDeliveryCompany,
      TArea,
      TAccountLoginLog,
      TAccountPlatform,
      TCartItem,
      TThirdPlatformConfig,
    ]),
  ],
  exports: [SequelizeModule],
  controllers: [],
  providers: [],
})
export class DBModule {}
